server:
  port: 7002
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mi?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: zhangyichi

mybatis:
  mapper-locations: classpath:com.neuedu.miserver.mapper/*.xml
  type-aliases-package: com.neuedu.miserver.po

